apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "0 0 * * *" # Daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongo-backup
              image: mongo:6.0
              command:
                - /bin/sh
                - -c
                - |
                  mongodump --uri="mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017" --archive=/backup/backup-$(date +%Y-%m-%d).archive
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
              env:
                - name: MONGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: username
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: password
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
